title: tpuz
description: Manage GCP TPU & GPU VMs from your terminal
url: "https://www.tahabouhsine.com"
baseurl: "/tpuz"
markdown: kramdown

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - getting-started.md
  - guide.md
  - gpu.md
  - secrets.md
  - best-practices.md
